export type { Props as LocaleCookieProps } from "./LocaleCookie.astro"
export { default as LocaleCookie } from "./LocaleCookie.astro"
export type { Props as LocaleHreflangProps } from "./LocaleHreflang.astro"
export { default as LocaleHreflang } from "./LocaleHreflang.astro"
export { default as LocaleRedirect } from "./LocaleRedirect.astro"
